
---
- hosts: Switch-01
  gather_facts: false
  connection: local


  tasks:
    - name: show run
      ios_command:
#       provider: "{{ cli }}"
       commands: show run
      register: config

    - copy:
        content: "{{ config.stdout[0] }}"
        dest: "/Users/mymac/Desktop/Ansible/Backup/{{ inventory_hostname }} {{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.txt"
